name: Tests

on: [pull_request]

jobs:
  build:
    name: "Units Test & Verify Bundle Size"

    runs-on: ubuntu-latest

    steps:
    - name: "Clone Repository"
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: "Install Node"
      uses: actions/setup-node@v3.6.0
      with:
        node-version: '18'

    - name: "Install Project Dependencies"
      shell: bash
      run: npm install

    - name: "Unit tests"
      shell: bash
      run: |
        Xvfb -ac :99 -screen 0 1280x1024x16 &
        export DISPLAY=:99
        npm run testci:mobxangular
    
    - name: "Compare bundle sizes"
      uses: preactjs/compressed-size-action@2.5.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        build-script: "build:mobx-angular"
